### ISSUE TITLE
Issue with French Subtitles

### ISSUE THREAD

**Issue by TORCHEBUGNE** [jacklul/USharpVideo-Subtitles#5] opened 2023-12-02 14:27 UTC
Hi ! Sorry for my english, I've an issue with French Subtitles, when I load it, I ve issue with special characters (é à ç etc...)
Subtitle load it like "?" inside a black square.

Do you know how I can solve this thing ? 

Thank you ! 

B4rTux_

**Comment by jacklul** [comment] 2023-12-02 15:02
Pretty sure they have to be in UTF-8 format to display correctly
If the world overrides the font then this can also be the cause

**Comment by TORCHEBUGNE** [comment] 2024-01-25 09:41
Oh sorry I don't see your answer me, thanks you, but I can't do it anymore, I change my world to Unity 2022 and the subtitles doesnt work anymore :'(

**Comment by jacklul** [comment] 2024-01-25 10:33
Unity change should not break Udon prefabs, thought I haven't looked into upgrading any of my content yet.

Perhaps a failed upgrade procedure?

**Comment by jacklul** [comment] 2024-01-29 11:59
@TORCHEBUGNE is the error the same as in here https://github.com/jacklul/USharpVideo-Subtitles/issues/6 ?

**Comment by jacklul** [comment] 2024-05-05 20:31
I am closing this because of no answer

**Closed as completed by jacklul** 2024-05-05 20:31 UTC
